// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh7HagwpsgpvzOmdWliMTXnDxCnUG28Wo',
    appId: '1:526249125108:web:da9f6fd2a328ab38c52aa1',
    messagingSenderId: '526249125108',
    projectId: 'swift2024app',
    authDomain: 'swift2024app.firebaseapp.com',
    storageBucket: 'swift2024app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4F9nYDqD6iWXHnw12awFhkoYyJAH1jX0',
    appId: '1:526249125108:android:295da0e8cb303e91c52aa1',
    messagingSenderId: '526249125108',
    projectId: 'swift2024app',
    storageBucket: 'swift2024app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ZO0cahdzw60qWvvbWTUKGJBGA7n49Aw',
    appId: '1:526249125108:ios:5c6957ed39c77e05c52aa1',
    messagingSenderId: '526249125108',
    projectId: 'swift2024app',
    storageBucket: 'swift2024app.appspot.com',
    iosBundleId: 'jp.ac.fun.swift2024tourism',
  );
}
