name: Run Dart Formatter

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  dart_format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        name: setup fvm flutter

      - shell: bash
        run: flutter --version
      
      - name: run pub get
        run: flutter pub get
        
      - name: dart format
        run: dart format -l 140 $(find lib -name "*.dart" -not -wholename "**/*.g*" -not -wholename "**/*.freezed.*" -not -wholename "**/firebase_options.dart" -not -wholename "**/oss_licenses.dart")
    
      - uses: stefanzweifel/git-auto-commit-action@v5
        name: commit
        with:
          commit_message: 'bot: run formatterr'
          commit_options: '--no-verify --signoff'
